// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnoepwhfxducbbxztvvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ub2Vwd2hmeGR1Y2JieHp0dnZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MjQ2MzgsImV4cCI6MjA2NzUwMDYzOH0.5_5aLVL4LV2VXM6xy7uJDBS1RyGNBPdj1-xOUk2kGd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});